[package]
name = "redis-rs"
version = "0.0.1"
authors = ["Pin Fang <fpfangpin@hotmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.59"
bytes = "1.3.0"  
thiserror = "1.0.32"
tokio = { version = "1.23.0", features = ["full"] } 
clap = { version = "4.5.20", features = ["derive"] }
